CREATE DATABASE EF

USE EF


CREATE TABLE ALUMNOS
(
ID INT IDENTITY PRIMARY KEY,
NOMBRE VARCHAR(100),
CARNET VARCHAR(50),
IDCURSO INT,
ESTADO VARCHAR(1)
)

CREATE TABLE CURSO 
(
ID INT IDENTITY PRIMARY KEY,
NOMBRE VARCHAR(50)
)

CREATE TABLE NOTAS
(
ID INT IDENTITY PRIMARY KEY,
NOTA INT,
IDCURSO INT,
ESTADO AS CASE WHEN NOTA > 61 THEN 'APROBADO' ELSE 'REPROBADO' END
)

ALTER TABLE ALUMNOS ADD CONSTRAINT FK_ALUMNOS_CURSO FOREIGN KEY (IDCURSO) REFERENCES CURSO (ID)
ALTER TABLE NOTAS ADD CONSTRAINT FK_NOTAS_CURSO FOREIGN KEY (IDCURSO) REFERENCES CURSO (ID)


CREATE PROCEDURE SP_ALUMNOS
@ID INT,
@NOMBRE VARCHAR(100),
@CARNET VARCHAR(50),
@IDCURSO INT,
@ESTADO VARCHAR(1),
@OPTIONS VARCHAR(100)
AS
BEGIN
	IF (@OPTIONS='Insert')
	BEGIN
		INSERT INTO ALUMNOS VALUES(
		@NOMBRE,@CARNET,@IDCURSO,@ESTADO)
	END
	IF (@OPTIONS='Update')
	BEGIN
		UPDATE ALUMNOS SET NOMBRE=@NOMBRE,CARNET=@CARNET,
		IDCURSO=@IDCURSO,ESTADO=@ESTADO
		WHERE ID=@ID
	END
	IF (@OPTIONS='Delete')
	BEGIN
		DELETE FROM ALUMNOS WHERE ID=@ID	
	END
	IF (@OPTIONS='GetId')
	BEGIN
		SELECT * FROM ALUMNOS WHERE ID=@ID 
	END
	SELECT * FROM ALUMNOS
END
GO

CREATE PROCEDURE SP_CURSOS
@ID INT,
@NOMBRE VARCHAR(50),
@OPTIONS VARCHAR(100)
AS
BEGIN
	IF (@OPTIONS='Insert')
	BEGIN
		INSERT INTO CURSO VALUES(
		@NOMBRE)
	END
	IF (@OPTIONS='Update')
	BEGIN
		UPDATE CURSO SET NOMBRE=@NOMBRE
		WHERE ID=@ID
	END
	IF (@OPTIONS='Delete')
	BEGIN
		DELETE FROM CURSO WHERE ID=@ID	
	END
	IF (@OPTIONS='GetId')
	BEGIN
		SELECT * FROM CURSO WHERE ID=@ID 
	END
	SELECT * FROM CURSO
END
GO

CREATE PROCEDURE SP_NOTA
@ID INT,
@NOTA INT,
@IDCURSO INT,
@OPTIONS VARCHAR(100)
AS
BEGIN
	IF (@OPTIONS='Insert')
	BEGIN
		INSERT INTO NOTAS VALUES(
		@NOTA,@IDCURSO)
	END
	IF (@OPTIONS='Update')
	BEGIN
		UPDATE NOTAS SET NOTA=@NOTA, IDCURSO=@IDCURSO
		WHERE ID=@ID
	END
	IF (@OPTIONS='Delete')
	BEGIN
		DELETE FROM NOTAS WHERE ID=@ID	
	END
	IF (@OPTIONS='GetId')
	BEGIN
		SELECT * FROM NOTAS WHERE ID=@ID 
	END
	SELECT * FROM NOTAS
END
GO